//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEntities : DbContext
    {
        public WebEntities(string connectionString)
            : base(new System.Data.Entity.Core.Objects.ObjectContext(new System.Data.Entity.Core.EntityClient.EntityConnection(connectionString), true),true)
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoleClaim> AspNetRoleClaims { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<AspNetUserToken> AspNetUserTokens { get; set; }
        public virtual DbSet<AttributeSourceLanguage> AttributeSourceLanguages { get; set; }
        public virtual DbSet<AttributeSource> AttributeSources { get; set; }
        public virtual DbSet<CompanyBranch> CompanyBranches { get; set; }
        public virtual DbSet<CompanyDomain> CompanyDomains { get; set; }
        public virtual DbSet<CompanyLanguage> CompanyLanguages { get; set; }
        public virtual DbSet<ItemImage> ItemImages { get; set; }
        public virtual DbSet<ItemLanguage> ItemLanguages { get; set; }
        public virtual DbSet<ItemMedia> ItemMedias { get; set; }
        public virtual DbSet<ItemProductAddOn> ItemProductAddOns { get; set; }
        public virtual DbSet<ItemProductGroupon> ItemProductGroupons { get; set; }
        public virtual DbSet<ItemProduct> ItemProducts { get; set; }
        public virtual DbSet<ItemRelated> ItemRelateds { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<ModuleConfigDetail> ModuleConfigDetails { get; set; }
        public virtual DbSet<ModuleConfigParam> ModuleConfigParams { get; set; }
        public virtual DbSet<ModuleConfig> ModuleConfigs { get; set; }
        public virtual DbSet<ModuleParam> ModuleParams { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleSkin> ModuleSkins { get; set; }
        public virtual DbSet<OrderProduct> OrderProducts { get; set; }
        public virtual DbSet<TemplateComponent> TemplateComponents { get; set; }
        public virtual DbSet<TemplatePosition> TemplatePositions { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateSkin> TemplateSkins { get; set; }
        public virtual DbSet<ThirdParty> ThirdParties { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<AttributeLanguage> AttributeLanguages { get; set; }
        public virtual DbSet<AttributeValueLanguage> AttributeValueLanguages { get; set; }
        public virtual DbSet<AttributeValue> AttributeValues { get; set; }
        public virtual DbSet<CompanyLanguageConfig> CompanyLanguageConfigs { get; set; }
        public virtual DbSet<TemplateLanguageKey> TemplateLanguageKeys { get; set; }
        public virtual DbSet<ItemAttribute> ItemAttributes { get; set; }
        public virtual DbSet<WebConfig> WebConfigs { get; set; }
        public virtual DbSet<ItemEvent> ItemEvents { get; set; }
        public virtual DbSet<AttributeCategory> AttributeCategories { get; set; }
        public virtual DbSet<Attribute> Attributes { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<ItemReview> ItemReviews { get; set; }
        public virtual DbSet<ItemArticle> ItemArticles { get; set; }
        public virtual DbSet<WebInfo> WebInfos { get; set; }
        public virtual DbSet<SEO> SEOs { get; set; }
        public virtual DbSet<ItemTag> ItemTags { get; set; }
        public virtual DbSet<OrderDelivery> OrderDeliveries { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<ContactAttribute> ContactAttributes { get; set; }
        public virtual DbSet<ItemCategoryComponent> ItemCategoryComponents { get; set; }
        public virtual DbSet<ItemCategory> ItemCategories { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<AttributeOrder> AttributeOrders { get; set; }
        public virtual DbSet<OrderAttribute> OrderAttributes { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<AttributeContact> AttributeContacts { get; set; }
    }
}
