//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeValue
    {
        public AttributeValue()
        {
            this.AttributeValueLanguages = new HashSet<AttributeValueLanguage>();
        }
    
        public string Id { get; set; }
        public System.Guid SourceId { get; set; }
    
        public virtual AttributeSource AttributeSource { get; set; }
        public virtual ICollection<AttributeValueLanguage> AttributeValueLanguages { get; set; }
    }
}
