//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttributeCategory
    {
        public string AttributeId { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid CategoryId { get; set; }
        public int Order { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
