//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attribute
    {
        public Attribute()
        {
            this.AttributeCategories = new HashSet<AttributeCategory>();
            this.AttributeLanguages = new HashSet<AttributeLanguage>();
            this.OrderAttributes = new HashSet<OrderAttribute>();
        }
    
        public string Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public Nullable<System.Guid> SourceId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<AttributeCategory> AttributeCategories { get; set; }
        public virtual ICollection<AttributeLanguage> AttributeLanguages { get; set; }
        public virtual AttributeSource AttributeSource { get; set; }
        public virtual Company Company { get; set; }
        public virtual AttributeOrder AttributeOrder { get; set; }
        public virtual ICollection<OrderAttribute> OrderAttributes { get; set; }
        public virtual AttributeContact AttributeContact { get; set; }
    }
}
