//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public Company()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Attributes = new HashSet<Attribute>();
            this.AttributeSources = new HashSet<AttributeSource>();
            this.CompanyBranches = new HashSet<CompanyBranch>();
            this.CompanyDetails = new HashSet<CompanyDetail>();
            this.CompanyDomains = new HashSet<CompanyDomain>();
            this.CompanyLanguageConfigs = new HashSet<CompanyLanguageConfig>();
            this.CompanyLanguages = new HashSet<CompanyLanguage>();
            this.Contacts = new HashSet<Contact>();
            this.Customers = new HashSet<Customer>();
            this.Items = new HashSet<Item>();
            this.ModuleConfigs = new HashSet<ModuleConfig>();
            this.SEOs = new HashSet<SEO>();
            this.ThirdParties = new HashSet<ThirdParty>();
            this.WebInfos = new HashSet<WebInfo>();
            this.AttributeOrders = new HashSet<AttributeOrder>();
            this.OrderAttributes = new HashSet<OrderAttribute>();
            this.Orders = new HashSet<Order>();
            this.AttributeContacts = new HashSet<AttributeContact>();
        }
    
        public System.Guid Id { get; set; }
        public string Image { get; set; }
        public string TaxCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public string Type { get; set; }
        public string TaxCodePlace { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public virtual ICollection<Attribute> Attributes { get; set; }
        public virtual ICollection<AttributeSource> AttributeSources { get; set; }
        public virtual ICollection<CompanyBranch> CompanyBranches { get; set; }
        public virtual ICollection<CompanyDetail> CompanyDetails { get; set; }
        public virtual ICollection<CompanyDomain> CompanyDomains { get; set; }
        public virtual ICollection<CompanyLanguageConfig> CompanyLanguageConfigs { get; set; }
        public virtual ICollection<CompanyLanguage> CompanyLanguages { get; set; }
        public virtual ICollection<Contact> Contacts { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Item> Items { get; set; }
        public virtual ICollection<ModuleConfig> ModuleConfigs { get; set; }
        public virtual ICollection<SEO> SEOs { get; set; }
        public virtual ICollection<ThirdParty> ThirdParties { get; set; }
        public virtual WebConfig WebConfig { get; set; }
        public virtual ICollection<WebInfo> WebInfos { get; set; }
        public virtual ICollection<AttributeOrder> AttributeOrders { get; set; }
        public virtual ICollection<OrderAttribute> OrderAttributes { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<AttributeContact> AttributeContacts { get; set; }
    }
}
