//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        public System.Guid CompanyId { get; set; }
        public string LanguageCode { get; set; }
        public string FullName { get; set; }
        public string DisplayName { get; set; }
        public string Slogan { get; set; }
        public string Brief { get; set; }
        public string AboutUs { get; set; }
        public string Motto { get; set; }
        public string NickName { get; set; }
        public string JobTitle { get; set; }
        public string CoreValues { get; set; }
        public string Mission { get; set; }
        public string Vision { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
