//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemProduct
    {
        public ItemProduct()
        {
            this.ItemProductAddOns = new HashSet<ItemProductAddOn>();
            this.ItemProductAddOns1 = new HashSet<ItemProductAddOn>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public System.Guid CategoryId { get; set; }
        public System.Guid ItemId { get; set; }
        public decimal Price { get; set; }
        public string Code { get; set; }
        public int SaleMin { get; set; }
        public decimal Discount { get; set; }
        public int DiscountType { get; set; }
    
        public virtual ICollection<ItemProductAddOn> ItemProductAddOns { get; set; }
        public virtual ICollection<ItemProductAddOn> ItemProductAddOns1 { get; set; }
        public virtual ItemProductGroupon ItemProductGroupon { get; set; }
        public virtual Item Item { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
