//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemImages = new HashSet<ItemImage>();
            this.ItemLanguages = new HashSet<ItemLanguage>();
            this.ItemAttributes = new HashSet<ItemAttribute>();
            this.SEOs = new HashSet<SEO>();
            this.ItemTags = new HashSet<ItemTag>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Image { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsPublished { get; set; }
        public int Order { get; set; }
        public int View { get; set; }
    
        public virtual ICollection<ItemImage> ItemImages { get; set; }
        public virtual ICollection<ItemLanguage> ItemLanguages { get; set; }
        public virtual ItemMedia ItemMedia { get; set; }
        public virtual ItemProduct ItemProduct { get; set; }
        public virtual Menu Menu { get; set; }
        public virtual ICollection<ItemAttribute> ItemAttributes { get; set; }
        public virtual ItemEvent ItemEvent { get; set; }
        public virtual ItemReview ItemReview { get; set; }
        public virtual ItemArticle ItemArticle { get; set; }
        public virtual ICollection<SEO> SEOs { get; set; }
        public virtual ICollection<ItemTag> ItemTags { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Company Company { get; set; }
    }
}
