//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemCategory
    {
        public ItemCategory()
        {
            this.AttributeCategories = new HashSet<AttributeCategory>();
            this.ItemArticles = new HashSet<ItemArticle>();
            this.ItemCategories1 = new HashSet<ItemCategory>();
            this.ItemMedias = new HashSet<ItemMedia>();
            this.ItemProducts = new HashSet<ItemProduct>();
        }
    
        public System.Guid ItemId { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> ParentId { get; set; }
        public bool SEO { get; set; }
    
        public virtual ICollection<AttributeCategory> AttributeCategories { get; set; }
        public virtual ICollection<ItemArticle> ItemArticles { get; set; }
        public virtual ICollection<ItemCategory> ItemCategories1 { get; set; }
        public virtual ItemCategory ItemCategory1 { get; set; }
        public virtual Item Item { get; set; }
        public virtual ItemCategoryComponent ItemCategoryComponent { get; set; }
        public virtual ICollection<ItemMedia> ItemMedias { get; set; }
        public virtual ICollection<ItemProduct> ItemProducts { get; set; }
    }
}
