//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemArticle
    {
        public System.Guid ItemId { get; set; }
        public System.Guid CategoryId { get; set; }
        public System.DateTime DisplayDate { get; set; }
        public string HTML { get; set; }
        public string Type { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
