//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemReview
    {
        public System.Guid ItemId { get; set; }
        public System.Guid ReviewFor { get; set; }
        public int Vote { get; set; }
        public string Comment { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public bool IsBuyer { get; set; }
        public bool IsReply { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
