//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemComment
    {
        public ItemComment()
        {
            this.ItemComments1 = new HashSet<ItemComment>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ItemId { get; set; }
        public Nullable<System.Guid> ReplyId { get; set; }
        public string Comment { get; set; }
        public string ClientId { get; set; }
        public string Name { get; set; }
        public System.DateTime CommentDate { get; set; }
        public bool Approve { get; set; }
    
        public virtual ICollection<ItemComment> ItemComments1 { get; set; }
        public virtual ItemComment ItemComment1 { get; set; }
        public virtual Item Item { get; set; }
    }
}
