//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleSkin
    {
        public System.Guid Id { get; set; }
        public int HeaderFontSize { get; set; }
        public string HeaderFontColor { get; set; }
        public string HeaderBackground { get; set; }
        public int BodyFontSize { get; set; }
        public string BodyFontColor { get; set; }
        public string BodyBackground { get; set; }
        public int Height { get; set; }
        public int Width { get; set; }
    
        public virtual ModuleConfig ModuleConfig { get; set; }
    }
}
