//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDelivery
    {
        public System.Guid OrderId { get; set; }
        public int DeliveryId { get; set; }
        public string DeliveryCode { get; set; }
        public decimal DeliveryFee { get; set; }
        public bool COD { get; set; }
        public string DeliveryNote { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
