//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.OrderAttributes = new HashSet<OrderAttribute>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public System.Guid CustomerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReceiveDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Note { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerName { get; set; }
        public string CustomerPhone { get; set; }
        public decimal Discount { get; set; }
        public int DiscountType { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual ICollection<OrderAttribute> OrderAttributes { get; set; }
        public virtual OrderDelivery OrderDelivery { get; set; }
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
    }
}
