//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderAttribute
    {
        public System.Guid OrderId { get; set; }
        public string AttributeId { get; set; }
        public string LanguageCode { get; set; }
        public System.Guid CompanyId { get; set; }
        public string Value { get; set; }
    
        public virtual Attribute Attribute { get; set; }
        public virtual Company Company { get; set; }
        public virtual Order Order { get; set; }
    }
}
