//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEO
    {
        public System.Guid Id { get; set; }
        public System.Guid CompanyId { get; set; }
        public Nullable<System.Guid> ItemId { get; set; }
        public string LanguageCode { get; set; }
        public string Url { get; set; }
        public string SeoUrl { get; set; }
        public string Title { get; set; }
        public string MetaKeyWord { get; set; }
        public string MetaDescription { get; set; }
        public Nullable<System.Guid> NoItemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Company Company { get; set; }
    }
}
