//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebConfig
    {
        public System.Guid Id { get; set; }
        public string TemplateName { get; set; }
        public string WebIcon { get; set; }
        public string Header { get; set; }
        public string Background { get; set; }
        public bool CanRightClick { get; set; }
        public bool CanSelectCopy { get; set; }
        public string Keys { get; set; }
        public Nullable<System.DateTime> RegisDate { get; set; }
        public Nullable<System.DateTime> ExperDate { get; set; }
        public bool Hierarchy { get; set; }
        public string FontColor { get; set; }
        public int FontSize { get; set; }
        public string Image { get; set; }
    
        public virtual Template Template { get; set; }
        public virtual Company Company { get; set; }
    }
}
